version: 2.1

# Define the jobs we want to run for this project
jobs:

  build:
    docker:
      - image: cimg/node:19.0.0
      - image: mongo:4.2.0
    resource_class: medium
    steps:
      - checkout
      - run: npm install
      - run: npm run test
